MedHelper.Web/Controllers/MedicineController.cs
using MedHelper.BLL.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;
using MedHelper.BLL.Dto.Medicine;
using MedHelper.BLL.Dto.Patient;
using Microsoft.AspNetCore.Authorization;
using MedHelper.BLL.Dto.Responses;
using System.Collections.Generic;
using Microsoft.AspNetCore.Http;
using System.Net;
using System.Security.Claims;
using MedHelper.DAL.Entities;
using Microsoft.AspNetCore.Identity;

namespace MedHelper.Web.Controllers
{
    public class MedicineController : Controller
    {
        IMedicineService _medicineService;
        private readonly UserManager<User> _userManager;
        public MedicineController(IMedicineService medicineService, UserManager<User> userManager)
        {
            _medicineService = medicineService;
            _userManager = userManager;
        }

        [HttpGet]
        // [Route("Medicine/{id}")]
        public async Task<IActionResult> Index(int Id)
        {
            var medicine = await _medicineService.GetByIdAsync(Id);
            TempMedicineResponse response = new TempMedicineResponse() { 
                Id = medicine.Id,
                Name = medicine.Name,
                Group = medicine.Group,
                Compositions = medicine.Compositions.ToList(),
                Contraindications = medicine.Contraindications.ToList(),
                MedicineInteractions = medicine.MedicineInteractions.ToList()
            };
           
            return View(response);
        }
        
        [HttpGet]
        [Authorize(Roles ="Admin")]
        public IActionResult Add()
        {
            ViewBag.MedicineCompositions = _medicineService.GetAllCompositions();
            ViewBag.Groups = _medicineService.GetAllPharmacotherapeuticGroups();
            ViewBag.Contraindications = _medicineService.GetAllDiseases();
            return View();
        }
        
        [HttpPost]
        [Authorize(Roles ="Admin")]
        public async Task<IActionResult> AddAsync(CreateMedicineDto medicine)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.MedicineCompositions = _medicineService.GetAllCompositions();
                ViewBag.Groups = _medicineService.GetAllPharmacotherapeuticGroups();
                ViewBag.Contraindications = _medicineService.GetAllDiseases();
                return View();
            }
            
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = await _userManager.FindByIdAsync(userId);
            medicine.UserId = user.Id;
            
            await _medicineService.AddAsync(medicine);
            return RedirectToAction(nameof(ViewAllMedicines));
        }

        [HttpGet]
        [Route("Medicines")]
        public ActionResult ViewAllMedicines(string search)
        {
            List<MedicineResponse> medicines =  _medicineService.GetAll(search).ToList();

            ViewMedicinesResponse response = new ViewMedicinesResponse() { Medicines = medicines};

            return View(response);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _medicineService.DeleteByIdAsync(id);
            return RedirectToAction(nameof(ViewAllMedicines));
        }

         // [HttpPost]
         // public ActionResult Delete(int id, FormCollection collection)
         // {
         //     var res = _medicineService.DeleteByIdAsync(id);
         //     if (res == null)
         //         return NotFound();
         //     return RedirectToAction(nameof(Index));
         // }
         //
         // [HttpGet]
         // public IActionResult Delete([FromRoute] int id)
         // {
         //     var res = _medicineService.DeleteByIdAsync(id);
         //     if (res == null)
         //         return NotFound();
         //     return RedirectToAction(nameof(Index));
         // }

    }
}

MedHelper.Web/Controllers/PatientController.cs
using MedHelper.BLL.Interfaces;
using MedHelper.Web.Models;
using Microsoft.AspNetCore.Mvc;
using MedHelper.BLL.Dto.Patient;
using Microsoft.AspNetCore.Authorization;
using System.Threading.Tasks;
using System.Linq;
using System.Collections.Generic;
using System;
using System.Security.Claims;
using MedHelper.BLL.Dto.Responses;
using MedHelper.DAL.Entities;
using Microsoft.AspNetCore.Identity;

namespace MedHelper.Web.Controllers
{
    public class PatientController : Controller
    {
        private const string DOCTOR_PAGE = "https://localhost:7241/Doctor";
        private IPatientService _patientService;
        IMedicineService _medicineService;
        private readonly UserManager<User> _userManager;

        public PatientController(IPatientService patientService, IMedicineService medicineService, UserManager<User> userManager)
        { 
            _patientService = patientService;
            _medicineService = medicineService;
            _userManager = userManager;
        }
        
        
        [HttpGet]
        [Route("Patient/{id}")]
        public async Task<IActionResult> Index(int id, string search)
        {
            var patient = await _patientService.GetByIdAsync(id);
            var allMedicines = await _patientService.GetAllMedicinesForPatientAsync(id, search);

            PatientResponse response = new PatientResponse() {
                Id = patient.Id,
                FirstName = patient.FirstName,
                LastName = patient.LastName,
                Birthdate = patient.Birthdate,
                Gender = patient.Gender,
                Medicines = patient.Medicines.ToList(),
                Diseases = patient.Diseases.ToList(),
                AllMedicines = allMedicines.ToList()
            };
            
            return View(response);
        }

        [HttpGet, ActionName("Add")]
        [Authorize]
        [Route("Patient/add")]
        public IActionResult Add()
        {
            ViewBag.Medicines = _medicineService.GetAll();
            ViewBag.Diseases = _medicineService.GetAllDiseases();
            return View();
        }
        
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> AddAsync(CreatePatientDto patient)
        {
            // if (!ModelState.IsValid)
            // {
            //     ViewBag.Medicines = _medicineService.GetAll();
            //     ViewBag.Diseases = _medicineService.GetAllDiseases();
            //     return View();
            // }
            
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            patient.UserId = Convert.ToInt32(userId);

            patient.Medicines = _medicineService.CreateMedicinesFromString(patient.TempMedicines).ToList();
            patient.Diseases = _medicineService.CreateDiseasesFromString(patient.TempDiseases).ToList();
            
            await _patientService.AddAsync(patient);
            return Redirect(DOCTOR_PAGE);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _patientService.DeleteByIdAsync(id);
            return Redirect(DOCTOR_PAGE);
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Edit(int id)
        {
            var patient = await _patientService.GetByIdAsync(id);

            var tempMedicines = patient.Medicines.Aggregate("", (current, i) => current + (i.Name + "\r\n"));
            var tempDiseases = patient.Diseases.Aggregate("", (current, i) => current + (i.Title + "\r\n"));

            UpdatePatientDto update = new UpdatePatientDto()
            {
                Birthdate = patient.Birthdate,
                FirstName = patient.FirstName,
                LastName = patient.LastName,
                TempMedicines = tempMedicines,
                TempDiseases = tempDiseases,
                Gender = patient.Gender,
                Id = patient.Id
            };

            ViewBag.Medicines = _medicineService.GetAll();
            ViewBag.Diseases = _medicineService.GetAllDiseases();
            return View(update);
        }

        [HttpPost, ActionName("Edit")]
        [Authorize]
        public async Task<IActionResult> Edit(UpdatePatientDto patient)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            patient.UserId = Convert.ToInt32(userId);

            patient.Medicines = _medicineService.CreateMedicinesFromString(patient.TempMedicines).ToList();
            patient.Diseases = _medicineService.CreateDiseasesFromString(patient.TempDiseases).ToList();

            await _patientService.UpdateAsync(patient);
            return Redirect(DOCTOR_PAGE);
        }
    }
}

MedHelper.Web/Views/Patient/Add.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model MedHelper.BLL.Dto.Patient.CreatePatientDto
@{
    ViewData["Title"] = "Add patient";
}

<head xmlns="http://www.w3.org/1999/html">
    <link rel="stylesheet" href=~/css/Patient/Addpp.css />
    @* <title>@ViewData["Title"]</title> *@
</head>

<div class="add-edit-patient-content" onload="Init()">
    <h1> Додати пацієнта </h1>
    <hr>
    <div class="container">
        <form asp-controller="Patient" asp-action="Add" method="post" class="add-patient-form">
            <div class="container-left">
                <div class="d-flex flex-column">
                    <label> Ім'я: </label>
                    <input type="text" name="firstName" asp-for="FirstName" placeholder="ім'я" size="15" required />
                </div>
                <div class="d-flex flex-column mt-4">
                    <label> Прізвище: </label>
                    <input type="text" name="lastName" asp-for="LastName" placeholder="прізвище" size="15" required />
                </div>
                <div class="d-flex flex-column mt-4">
                    <label> Дата народження: </label>
                    @Html.TextBoxFor(Model => Model.Birthdate, new { type = "date" })
                </div>
                <div class="d-flex flex-column mt-4">
                    <label> Cтать: </label>
                    <input type="text" name="gender" asp-for="Gender" placeholder="стать" size="15" required />
                </div>

                <div class="d-flex flex-column mt-4">
                    <label>
                        Список препаратів, які вживає пацієнт:
                    </label>

                    <div>
                        <datalist id="MedicineSuggestions">
                            @foreach (var item in ViewBag.Medicines)
                            {
                                <option id=@item.Id>@item.Name</option>
                            }
                        </datalist>
                        <input type="text" onfocus="this.value=''" onchange="this.blur();" id="medicine_suggestions_input" autoComplete="on" class="drop-down list" placeholder="препарат" list="MedicineSuggestions" />
                    </div>
                    <textarea asp-for="TempMedicines" cols="80" rows="5" id="selectedMedicineOptionsTextArea" class="mt-1"></textarea>
                    <button type="button" class="btn btn-danger mt-1" style="width: 65%;" onclick="clearSelectedMedicineOptionsTextArea()">Видалити</button>
                </div>
                <div class="d-flex flex-column mt-4">
                    <label>
                        Медична карта:
                    </label>
                    <div>
                        <datalist id="ContraindicationSuggestions">
                            @foreach (var item in ViewBag.Diseases)
                            {
                                <option id=@item.Id>@item.Title</option>
                            }
                        </datalist>
                        <input type="text" onfocus="this.value=''" onchange="this.blur();" id="contraindication_suggestions_input" autoComplete="on" class="drop-down list" placeholder="противопоказання" list="ContraindicationSuggestions" />
                    </div>
                    <textarea asp-for="TempDiseases" cols="80" rows="5" id="selectedContraindicationOptionsTextArea" class="mt-1"></textarea>
                    <button type="button" class="btn btn-danger mt-1" style="width: 65%;" onclick="clearSelectedContraindicationOptionsTextArea()">Видалити</button>
                </div>
            </div>
            <hr />
            <button type="submit" class="submit-button btn btn-primary mt-3" style="width: 65%;">Додати пацієнта</button>
        </form>
    </div>

    <script>
        //const storageSuggestions = document.getElementById('storageSuggestions').childNodes;
        const MedicineSuggestionsInput = document.getElementById("medicine_suggestions_input");
        let eventSource = null;

        MedicineSuggestionsInput.addEventListener('keydown', (event) => {
            if (event.key === 'Enter') {
                event.preventDefault(); // не перекине на інший інпут
            }
            eventSource = event.key ? 'input' : 'list';
        });
        MedicineSuggestionsInput.addEventListener('input', (event) => {
            if (eventSource === 'list') {
                document.getElementById("selectedMedicineOptionsTextArea").innerHTML += event.target.value + '\n';
            }
        });
        function clearSelectedMedicineOptionsTextArea() {
            let splittedText = document.getElementById("selectedMedicineOptionsTextArea").innerHTML.split(/\r?\n/)
            splittedText.splice(-2)
            document.getElementById("selectedMedicineOptionsTextArea").innerHTML = splittedText.join('\n');
            document.getElementById("selectedMedicineOptionsTextArea").innerHTML += "\n";
        }


        const ContraindicationSuggestionsInput = document.getElementById("contraindication_suggestions_input");
        let eventSource2 = null;

        ContraindicationSuggestionsInput.addEventListener('keydown', (event) => {
            if (event.key === 'Enter') {
                event.preventDefault(); // не перекине на інший інпут
            }
            eventSource2 = event.key ? 'input' : 'list';
        });
        ContraindicationSuggestionsInput.addEventListener('input', (event) => {
            if (eventSource2 === 'list') {
                document.getElementById("selectedContraindicationOptionsTextArea").innerHTML += event.target.value + '\n';
            }
        });
        function clearSelectedContraindicationOptionsTextArea() {

            let splittedText = document.getElementById("selectedContraindicationOptionsTextArea").innerHTML.split(/\r?\n/)
            splittedText.splice(-2)
            document.getElementById("selectedContraindicationOptionsTextArea").innerHTML = splittedText.join('\n');
            document.getElementById("selectedContraindicationOptionsTextArea").innerHTML += "\n";
        }
    </script>
</div>

MedHelper.Web/Views/Patient/Edit.cshtml
@model MedHelper.BLL.Dto.Patient.UpdatePatientDto


<link rel="stylesheet" href=~/css/Patient/Addpp.css />
<div class="add-edit-patient-content" onload="Init()">
    <h1> Редагування інформації про пацієнта </h1>
    <hr>
    <div class="container">
        <form asp-controller="Patient" asp-action="Add" method="post" class="add-patient-form">
            <div class="container-left">

                <input hidden asp-for="Id" />


                <div class="d-flex flex-column">
                    <label> Ім'я: </label>
                    <input type="text" name="firstName" asp-for="FirstName" placeholder="ім'я" size="15" required />
                </div>

                <div class="d-flex flex-column mt-4">
                    <label> Прізвище: </label>
                    <input type="text" name="lastName" asp-for="LastName" placeholder="прізвище" size="15" required />
                </div>
                <div class="d-flex flex-column mt-4">
                    <label> Дата народження: </label>
                    @Html.TextBoxFor(Model => Model.Birthdate, "{0:yyyy-MM-dd}", new { type = "date" })
                </div>

                <div class="d-flex flex-column mt-4">
                    <label> Cтать: </label>
                    <input type="text" name="gender" asp-for="Gender" placeholder="стать" size="15" required />
                </div>
                @* <div> *@
                @*   <label> *@
                @*     Стать : *@
                @*   </label> *@
                @*   <br> *@
                @*   <input asp-for="Gender" type="radio" value="Male" name="gender" checked> Чоловік *@
                @*   <input asp-for="Gender" type="radio" value="Female" name="gender"> Жінка *@
                @* *@
                @* </div> *@
                @* <label> Список препаратів, які вживає пацієнт: </label> *@
                @* <input type="text" name="tempMedicines" asp-for="TempMedicines" placeholder="tempMedicines" size="15" required/> *@
                <div class="d-flex flex-column mt-4">
                    <label>
                        Список препаратів, які вживає пацієнт:
                    </label>

                    <div>
                        <datalist id="MedicineSuggestions">
                            @foreach (var item in ViewBag.Medicines)
                            {
                                <option id=@item.Id>@item.Name</option>
                            }
                        </datalist>
                        <input id="medicine_suggestions_input" type="text" onfocus="this.value=''" onchange="this.blur();" autoComplete="on" class="drop-down list" placeholder="препарат" list="MedicineSuggestions" />
                    </div>
                    <textarea asp-for="TempMedicines" cols="80" rows="5" id="selectedMedicineOptionsTextArea" class="mt-1"></textarea>
                    <button type="button" class="btn btn-danger mt-1" style="width: 65%;" onclick="clearSelectedMedicineOptionsTextArea()">Видалити</button>
                </div>
       
            <div class="d-flex flex-column mt-4">
                <label>
                    Медична карта:
                </label>

                <div>
                    <datalist id="ContraindicationSuggestions">
                        @foreach (var item in ViewBag.Diseases)
                        {
                            <option id=@item.Id>@item.Title</option>
                        }
                    </datalist>
                    <input type="text" onfocus="this.value=''" onchange="this.blur();" id="contraindication_suggestions_input" autoComplete="on" class="drop-down list" placeholder="противопоказання" list="ContraindicationSuggestions" />
                </div>
                <textarea asp-for="TempDiseases" cols="80" rows="5" id="selectedContraindicationOptionsTextArea" class="mt-1"></textarea>
                <button type="button" class="btn btn-danger mt-1" style="width: 65%;" onclick="clearSelectedContraindicationOptionsTextArea()">Видалити</button>
                @* <input type="text" name="tempDiseases" asp-for="TempDiseases" placeholder="tempDiseases" size="15" required/> *@
            </div>
    </div>
    <hr />
    <button type="submit" class="submit-button btn btn-primary mt-3" style="width: 65%;">Відредагувати пацієнта</button>
    </form>
</div>

    <script>
        //const storageSuggestions = document.getElementById('storageSuggestions').childNodes;
        const MedicineSuggestionsInput = document.getElementById("medicine_suggestions_input");
        let eventSource = null;

        MedicineSuggestionsInput.addEventListener('keydown', (event) => {
            if (event.key === 'Enter') {
                event.preventDefault(); // не перекине на інший інпут
            }
            eventSource = event.key ? 'input' : 'list';
        });
        MedicineSuggestionsInput.addEventListener('input', (event) => {
            if (eventSource === 'list') {
                document.getElementById("selectedMedicineOptionsTextArea").innerHTML += event.target.value + '\n';
            }
        });
        function clearSelectedMedicineOptionsTextArea() {
            let splittedText = document.getElementById("selectedMedicineOptionsTextArea").innerHTML.split(/\r?\n/)
            splittedText.splice(-2)
            document.getElementById("selectedMedicineOptionsTextArea").innerHTML = splittedText.join('\n');
            document.getElementById("selectedMedicineOptionsTextArea").innerHTML += "\n";
        }


        const ContraindicationSuggestionsInput = document.getElementById("contraindication_suggestions_input");
        let eventSource2 = null;

        ContraindicationSuggestionsInput.addEventListener('keydown', (event) => {
            if (event.key === 'Enter') {
                event.preventDefault(); // не перекине на інший інпут
            }
            eventSource2 = event.key ? 'input' : 'list';
        });
        ContraindicationSuggestionsInput.addEventListener('input', (event) => {
            if (eventSource2 === 'list') {
                document.getElementById("selectedContraindicationOptionsTextArea").innerHTML += event.target.value + '\n';
            }
        });
        function clearSelectedContraindicationOptionsTextArea() {

            let splittedText = document.getElementById("selectedContraindicationOptionsTextArea").innerHTML.split(/\r?\n/)
            splittedText.splice(-2)
            document.getElementById("selectedContraindicationOptionsTextArea").innerHTML = splittedText.join('\n');
            document.getElementById("selectedContraindicationOptionsTextArea").innerHTML += "\n";
        }
    </script>
</div>

MedHelper.Web/Views/Patient/Get.cshtml
@model MedHelper.BLL.Dto.Responses.PatientResponse

@{
    var fullname = string.Concat(Model.FirstName, " ", Model.LastName);
    var Medicines = Model.Medicines;
    var Diseases = Model.Diseases;
    var AllMedicines = Model.AllMedicines;
}

<link rel="stylesheet" href=~/css/PatientProfile.css type="text/css" />

<form asp-controller="Patient" asp-action="Get" method="get">

    <div class="patient-profile-content">
        <h1> @fullname </h1>
        <div class="profile-container">
            <div class="profile-container-left">
                <div class="edit-header">
                    <p>Інформація про пацієнта</p>
                    <img class="search-img" src="~/EditLogo.png" onclick="EditRedirect(@Model.Id)">
                </div>
                <div class="medicine-scroll-panel">
                    <div class="row">
                        <label>Стать:</label>
                        <input type="text" value=@Model.Gender disabled>
                    </div>

                    <div class="row">
                        <label>Вік:</label>
                        <input type="number" value=@((DateTime.Now.Year - Model.Birthdate.Year)) disabled>
                    </div>

                    <div class="row list">

                        <label> Список препаратів, які вживає пацієнт: </label>
                        @for (var i = 0; i < Medicines.Count; i++)
                        {
                            <p>@(i+1) @Medicines[i].Name</p>
                        }
                    </div>

                    <div class="row list">
                        <label> Медична карта: </label>
                        @for (var i = 0; i < Diseases.Count; i++)
                        {
                            <p>@(i+1) @Diseases[i].Title</p>
                        }
                    </div>
                </div>
            </div>

            <div class="profile-container-right">
                <div class="medicine-list">
                    <div class="search-part-medicine">
                        <img class="medicine-search-img" src=~/SearchLogo.png>
                        <input class="search" type="text" placeholder="Search.." asp-for="search">
                        <input type="submit" value="Знайти" style="float:right" />
                    </div>
                    <div class="medicine-scroll-panel">
                        @foreach (var item in AllMedicines)
                        {
                            <button class="button-medicine" type="button" onclick="location.href='@Url.Action("ViewMedicine", "Medicine", new { id = item.Id })'">@item.Name</button>
                        }
                    </div>
                </div>

            </div>
        </div>

    </div>
</form>
<script>
    EditRedirect = function (id) {
        window.location.href = `https://localhost:7241/Patient/${id}/Edit`
    }
    MedicineRedirect = function (id) {
        window.location.href = `https://localhost:7241/Medicine/${id}`
    }
</script>

MedHelper.Web/Views/Patient/Index.cshtml
@model MedHelper.BLL.Dto.Responses.PatientResponse

@{
    var fullname = string.Concat(Model.FirstName, " ", Model.LastName);
    var Medicines = Model.Medicines;
    var Diseases = Model.Diseases;
    var AllMedicines = Model.AllMedicines;
}

<link rel="stylesheet" href=~/css/PatientProfileblyat.css type="text/css" />

<form asp-controller="Patient" asp-action="Index" method="get">

    <div class="patient-profile-content">
        <h1> @fullname </h1>
        <div class="profile-container">
            <div class="profile-container-left">
                <div class="edit-header">
                    <p>Інформація про пацієнта</p>
                    <img class="search-img" src="~/EditLogo.png" onclick="location.href='@Url.Action("Edit", "Patient", new { id = Model.Id })'">
                </div>
                <div class="medicine-scroll-panel">
                    <div class="row">
                        <label>Стать:</label>
                        <input type="text" value=@Model.Gender disabled>
                    </div>

                    <div class="row">
                        <label>Вік:</label>
                        <input type="number" value=@((DateTime.Now.Year - Model.Birthdate.Year)) disabled>
                    </div>

                    <div class="row list">

                        <label> Список препаратів, які вживає пацієнт: </label>
                        @for (var i = 0; i < Medicines.Count; i++)
                        {
                            <p>@(i+1) @Medicines[i].Name</p>
                        }
                    </div>

                    <div class="row list">
                        <label> Медична карта: </label>
                        @for (var i = 0; i < Diseases.Count; i++)
                        {
                            <p>@(i+1) @Diseases[i].Title</p>
                        }
                    </div>
                </div>
            </div>

            <div class="profile-container-right">
                <div class="medicine-list">
                    <div class="search-part-medicine">
                        <img style="width: 1.5rem;height: 1.5rem;margin: 1rem;" src=~/SearchLogo.png>
                        <input style="flex: 1;" class="px-1 border-0" asp-for="search" type="text" placeholder="Search..">
                        <input type="submit" value="Знайти" class="btn btn-light py-0 px-2 m-1" style="height: 30px;" />
                    </div>
                    <div class="medicine-scroll-panel">
                        @foreach (var item in AllMedicines)
                        {
                            <button class="button-medicine" type="button" onclick="location.href='@Url.Action("Index", "Medicine", new { id = item.Id })'">@item.Name</button>
                        }
                    </div>
                </div>

            </div>
        </div>
    </div>
</form>
<form asp-controller="Patient" asp-action="Delete" method="post" asp-route-id="@Model.Id">
    <div class="w-100 d-flex align-items-center justify-content-center">
        <input type="submit" id="btn-delete" class="btn btn-danger m-0"
               onclick="return confirm('Ви впевнені, що хочете видалити пацієнта?')"
               value="Видалити" />
    </div>
</form>