MedHelper.Web/Models/LoginViewModel.cs
using Microsoft.AspNetCore.Authentication;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MedHelper.Web.Models
{
    public class LoginViewModel
    {

        [Required]
        [EmailAddress(ErrorMessage = "Please enter valid email")]
        [Display(Name = "EMAIL")]
        public string Email { get; set; }

        [Required]
        [Display(Name = "PASSWORD")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

    }
}

MedHelper.Web/Models/RegisterViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MedHelper.Web.Models
{
    public class RegisterViewModel
    {
        [Required]
        [Display(Name = "FIRST NAME")]
        public string FirstName { get; set; }

        [Required]
        [Display(Name = "LAST NAME")]
        public string LastName { get; set; }

        [Required]
        [EmailAddress(ErrorMessage = "Please enter valid email")]
        [Display(Name = "EMAIL")]
        public string Email { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "PASSWORD")]
        public string Password { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "CONFIRM PASSWORD")]
        public string Confirm { get; set; }
    }
}

MedHelper.Web/Controllers/AuthorizationController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using MedHelper.DAL.Entities;
using MedHelper.Web.Models;
using Microsoft.Extensions.DependencyInjection;

namespace MedHelper.Web.Controllers
{
    public class AuthorizationController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly RoleManager<Role> _roleManager;

        public AuthorizationController(UserManager<User> userManager, RoleManager<Role> roleManager)
        {
            _userManager = userManager;
            _roleManager = roleManager;
        }

        public ActionResult Register()
        {
            return View();
        }

        //POST: Register
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Register(User user)
        {
            if (await _userManager.FindByEmailAsync(user.Email) != null)
            {

                ViewBag.error = "Email already exists";
                return View();
            }
            // var newUser = user
            await _roleManager.CreateAsync(new Role() { Name = "Doctor" });
            user.UserName = user.FirstName + user.LastName;
            var createdUser = await _userManager.CreateAsync(user, user.Password);
            await _userManager.AddToRoleAsync(user, "Doctor");
            if (!createdUser.Succeeded)
            {

                ViewBag.error = "error";
                return View();
            }
            //Use roleManager
            //if (ModelState.IsValid)
            //{
            //    Role r = _context.Roles.FirstOrDefault(x => x.UserRole == "Doctor");
            //    UserRole ur = new UserRole { Role = r, User = _user };
            //    var check = _context.Users.FirstOrDefault(s => s.Email == _user.Email);
            //    if (check == null)
            //    {
            //        _context.Users.Add(_user);
            //        _context.UserRoles.Add(ur);
            //        _context.SaveChanges();
            //        return RedirectToAction("Index", "Home");
            //    }
            //    else
            //    {
            //        ViewBag.error = "Email already exists";
            //        return View();
            //    }
            //}
            return View("Login");


        }

        public ActionResult Login()
        {
            return View();
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Login(string email, string password)
        {

            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByEmailAsync(email);
                bool isPasswordValid = await _userManager.CheckPasswordAsync(user, password);
                if (!isPasswordValid)
                {
                    ViewBag.error = "Login failed";
                    return View("Login");
                }
                var userRole = await _userManager.GetRolesAsync(user);
                var claims = new List<Claim>() {
                    new Claim(ClaimTypes.NameIdentifier, Convert.ToString(user.Id)),
                        new Claim(ClaimTypes.Name, user.UserName),
                        new Claim(ClaimTypes.Role, userRole.First()),
                };
                //Initialize a new instance of the ClaimsIdentity with the claims and authentication scheme    
                var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                //Initialize a new instance of the ClaimsPrincipal with ClaimsIdentity    
                var principal = new ClaimsPrincipal(identity);
                //SignInAsync is a Extension method for Sign in a principal for the specified scheme.    
                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal, new AuthenticationProperties()
                {
                    IsPersistent = true
                }) ;

                return RedirectToAction("Index", "Home");
            }
            return View();
        }


        //Logout
        public async Task<ActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            return RedirectToAction("Login");
        }
    }
}

MedHelper.Web/Views/Authorization/Login.cshtml
@model MedHelper.Web.Models.LoginViewModel
@{
    ViewData["Title"] = "Login";
    Layout = null;
}

<link rel="stylesheet" href="~/css/authorization.css" type="text/css" />

<head>
    <title>@ViewData["Title"]</title>
</head>
<div class="row justify-content-md-center">
    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                Login
            </div>
            <hr>
            <div class="card-body">
                <div class="left-container">
                    @using (Html.BeginForm("Login", "Authorization", FormMethod.Post))
                    {

                        @Html.AntiForgeryToken()
                        <div class="form-group">
                            <div>
                                @Html.LabelFor(m => m.Email)
                            </div>
                            <div>
                                @Html.TextBoxFor(m => m.Email, "", new { @class = "form-control", @placeholder = "Email" })
                            </div>
                        </div>
                        <div class="form-group">
                            <div>
                                @Html.LabelFor(m => m.Password)
                            </div>
                            <div>
                                @Html.PasswordFor(m => m.Password, new { @class = "form-control", @placeholder = "Password" })
                            </div>
                        </div>
                        <div class="form-group">
                            <input type="submit" name="submit" class="btn btn-primary" value="Login" />

                        </div>

                    }
                </div>
                <div class="right-container">
                </div>

                @{if (ViewBag.error == "Login failed")
                    {
                <span style="color: red; margin-top: 20px;"> Login failed! </span>
                        }
                    }
            </div>
            </div>
    </div>
</div>

MedHelper.Web/Views/Authorization/Register.cshtml
@model MedHelper.Web.Models.RegisterViewModel
@{
    ViewData["Title"] = "Register";
    Layout = null;
}


<link rel="stylesheet" href="~/css/authorization.css" type="text/css" />
<div class="row justify-content-md-center">
    <div class="col-md-5">
        @using (Html.BeginForm("Register", "Authorization", FormMethod.Post))
        {
            //@Html.ValidationSummary()
            @Html.AntiForgeryToken()

            <div class="card">
                <div class="card-header">
                    <div class="card-title">Register</div>
                </div>
                <hr>
                <div class="card-body">
                    <div class="left-container">
                        <div class="form-group">
                            <div>
                                @Html.LabelFor(m => m.FirstName)
                            </div>
                            <div>
                                @Html.TextBoxFor(m => m.FirstName, "", new { @class = "form-control", @placeholder = "First Name" })
                            </div>
                            <div>
                                @Html.ValidationMessageFor(m => m.FirstName, "", new { @class = "badge badge-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            <div>
                                @Html.LabelFor(m => m.LastName)
                            </div>
                            <div>
                                @Html.TextBoxFor(m => m.LastName, "", new { @class = "form-control", @placeholder = "Last Name" })
                            </div>
                            <div>
                                @Html.ValidationMessageFor(m => m.LastName, "", new { @class = "badge badge-danger" })
                            </div>
                        </div>
                    </div>
                    <div class="right-container">
                        <div class="form-group">
                            <div>
                                @Html.LabelFor(m => m.Email)
                            </div>
                            <div>
                                @Html.TextBoxFor(m => m.Email, "", new { @class = "form-control", @placeholder = "Email" })
                            </div>
                            <div>
                                @Html.ValidationMessageFor(m => m.Email, "", new { @class = "badge badge-danger" })
                            </div>

                            @if (ViewBag.error != null)
                            {
                                <span style="color: red; margin-top: 20px;"> Login failed! </span>
                                @*<span class="badge badge-danger">@ViewBag.error</span>*@
                            }

                        </div>
                        <div class="form-group">
                            <div>
                                @Html.LabelFor(m => m.Password)
                            </div>
                            <div>
                                @Html.PasswordFor(m => m.Password, new { @class = "form-control", @placeholder = "Password" })
                            </div>
                            <div>
                                @Html.ValidationMessageFor(m => m.Password, "", new { @class = "badge badge-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            <input type="submit" name="submit" class="btn btn-danger" value="Register" />
                        </div>
                    </div>
                </div>
            </div>

        }
    </div>
</div>